<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Evo.Benchmarks</RootNamespace>
    <AssemblyName>Evo.Benchmarks</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Evo.Core\Evo.Core.csproj" />
  </ItemGroup>

</Project>
